# Generated by Django 3.0.2 on 2020-01-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=50, unique=True, verbose_name='Nombre.')),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del prodcuto', max_length=100, verbose_name='Descripcion')),
                ('imagen', models.CharField(help_text='URL de la imagen', max_length=100, verbose_name='Imagen Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
