# Generated by Django 3.0.2 on 2020-01-26 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20200125_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Ingrese URL de la imagen', verbose_name='Vencimiento:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Inglese el producto', max_length=50, unique=True, verbose_name='Nombre:'),
        ),
    ]
